Controllers/RotateController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.FileProviders;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Processing;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Threading.Tasks;


namespace ImageEditor.Controllers
{
    public class RotateController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(string filename, IFormFile blob)
        {
            try
            {
                using (var image = SixLabors.ImageSharp.Image.Load(blob.OpenReadStream()))
                {
                    string fileExtenstion = filename.Substring(filename.LastIndexOf('.'));

                    image.Mutate(x => x.Resize(image.Width, image.Height));
                    var newfileName = GenerateFileName("Photo_", fileExtenstion);
                    var filepath = new PhysicalFileProvider(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "Images")).Root + $@"\{newfileName}";
                    image.Save(filepath);


                    //using (Bitmap bitmap = new Bitmap(filepath))
                    //{
                    //    bitmap.RotateFlip(RotateFlipType.Rotate180FlipY);
                    //    var newfileName2 = GenerateFileName("Photo_", fileExtenstion);
                    //    var filepath2 = new PhysicalFileProvider(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "Images")).Root + $@"\{newfileName2}";
                    //    //image.Save(filepath2);
                    //    bitmap.Save(filepath2);

                    //    image.Dispose();
                    //    //MyFileName = newfileName;
                    //}


                }

                return Json(new { Message = "OK" });
            }
            catch (Exception)
            {
                return Json(new { Message = "ERROR" });
            }
        }

        public string GenerateFileName(string fileTypeName, string fileextenstion)
        {
            if (fileTypeName == null)
                throw new ArgumentNullException(nameof(fileTypeName));
            if (fileextenstion == null)
                throw new ArgumentNullException(nameof(fileextenstion));
            return $"{fileTypeName}_{DateTime.Now:yyyyMMddHHmmssfff}_{Guid.NewGuid():N}{fileextenstion}";
        }
    }
}

Views/Rotate/Index.cshtml
@{
    ViewData["title"] = "Square";
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Image Editor</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/croppie/2.6.5/croppie.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/croppie/2.6.5/croppie.min.js"></script>
    <style>
        .croppie-container {
            width: 100%;
            height: 80%;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="d-flex justify-content-center">
            <div class="col-md-6">
                <div class="card" style="margin-top:10px;">
                    <div class="card-header">Rotate Image</div>
                    <div class="card-body">
                        <div id="main-cropper"></div>
                        <input type="file" id="select" class="form-control" value="Choose Image" accept="image/*">
                        <button id="btnleft" style="margin-top: 10px;" name="btnleft" class="btn btn-success">Left</button>
                        <button id="btnright" style="margin-top: 10px;" name="btnright" class="btn btn-success">Right</button>
                        <button id="btnupload" style="margin-top: 10px;margin-left:288px" name="btnupload" class="btn btn-success">Mirror</button>
                    </div>
                </div>
            </div>
        </div>

        <a class="btn text-success" href="/Home/Index">Back to Home</a>
    </div>
</body>
</html>

<script type="text/javascript">

    //initialize Croppie
    var basic = $('#main-cropper').croppie
        ({
            viewport: { width: 100, height: 100 },
            boundary: { width: 300, height: 300 },
            showZoomer: false,
            enableOrientation: true
        });

    //Reading the contents of the specified Blob or File
    function readFile(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#main-cropper').croppie('bind', {
                    url: e.target.result,
                    orientation: 1
                });
            }
            reader.readAsDataURL(input.files[0]);
        }
    }

    // Change Event to Read file content from File input
    $('#select').on('change', function () { readFile(this); });


    $('#btnupload').on('click', function ()
    {
        basic.croppie('result', 'blob').then(function (blob)
        {
            var formData = new FormData();

            formData.append('filename', 'FileName.png');
            formData.append('blob', blob);
            var myAppUrlSettings =
            {
                MyUsefulUrl: '@Url.Action("Index", "Rotate")'
            }
            var request = new XMLHttpRequest();
            request.open('POST', myAppUrlSettings.MyUsefulUrl);
            request.send(formData);
            request.onreadystatechange = function () {
               // Call a function when the state changes.
                if (this.readyState === XMLHttpRequest.DONE && this.status === 200)
                {
                    var response = JSON.parse(request.responseText);

                    if (response.message == "OK")
                    {
                        alert('Photo Cropped Successfully!');
                        window.location.reload();
                    }
                    if (response.message == "ERROR")
                    {
                        window.location.reload();
                    }
                }
            }
        });
    });

    $('#btnleft').on('click', function ()
    {
        basic.croppie('rotate', parseInt($(this).data('rotate')));
    });

    $('#btnright').on('click', function ()
    {
        basic.croppie('rotate',parseInt($(this).data('rotate')));
    });
</script>